/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.assignment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testFeetToInches() {
        double result = Converter.unitConverter(12.0, "in", "ft");
        assertEquals(1.0, result, 0.001); 
    }

    @Test
    public void testFeetToMeters() {
        double result = Converter.unitConverter(3.0, "ft", "m");
        assertEquals(0.9144, result, 0.001); 
    }

    @Test
    public void testMilesToMeters() {
        double result = Converter.unitConverter(2.0, "mi", "m");
        assertEquals(3218.688, result, 0.001); 
    }

    @Test
    public void testMetersToInches() {
        double result = Converter.unitConverter(2.54, "m", "in");
        assertEquals(100.0, result, 0.001); 
    }

    @Test
    public void testInvalidUnit() {
        double result = Converter.unitConverter(10.0, "invalid", "ft");
        assertTrue(Double.isNaN(result)); //return NaN if the unit is invalid
    }

    @Test
    public void testSameUnit() {
        double result = Converter.unitConverter(5.0, "m", "m");
        assertEquals(5.0, result, 0.001); //
    }
}
